.github/workflows/ci.yml

chore: remove publish-dry-run

---

.github/workflows/job.yml

add actions

---

src/main.rs

add blacklist

---

src/main.rs

remove only

---

.github/workflows/job.yml
.github/workflows/job2.yml

test gcloud

---

.github/workflows/job2.yml

fix typo of filename

---

src/main.rs

add error that the count of locations is too small.

---

.github/workflows/ci.yml

fix ci error

---

.github/workflows/job2.yml
src/main.rs

feat: output non live camera list

---

src/main.rs

feat: add error messages

---

src/main.rs

feat: add quota check

---

src/main.rs

fix: change developper key

---

.github/workflows/job.yml
.github/workflows/job2.yml

ci: add developper key

---

src/main.rs

feat: rotate developper key

---

src/main.rs

refactor: refactor is_live

---

src/main.rs

refactor: refactor usage of youtube api

---

.github/workflows/job.yml
.github/workflows/job2.yml
src/main.rs

feat: live camera precheck

---

src/main.rs

feat: reduce dev key

---

src/main.rs

refactor: improve key

---

.github/workflows/job2.yml

ci: run Job2 everyday

---

src/main.rs

feat: add keys

---

.github/workflows/audit.yml
.github/workflows/ci.yml

https://github.com/rust-github/template/tree/main/template/.github/workflows

ci: update CI

---

.github/workflows/job.yml
.github/workflows/job2.yml

ci: update Jobs

---

src/main.rs

chore: update deprecated function

---

src/main.rs

refactor: move Regex to outside loop
